BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.PTC ADD
	PlanLimpiezaExistente varchar(255) NULL,
	PlanDrenajeExistente varchar(255) NULL
GO
ALTER TABLE dbo.PTC SET (LOCK_ESCALATION = TABLE)
GO
COMMIT