BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.PTCPTCPersonas
	(
	NroPTC numeric(18, 0) NOT NULL,
	Documento varchar(30) NOT NULL,
	IdTipoDocumento numeric(18, 0) NOT NULL,
	FechaHora datetime NOT NULL,
	IdUsuario varchar(30) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PTCPTCPersonas ADD CONSTRAINT
	PK_PTCPTCPersonas PRIMARY KEY CLUSTERED 
	(
	NroPTC,
	Documento,
	IdTipoDocumento
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PTCPTCPersonas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT