BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.PTCVinculados
	(
	NroPTCPredecesor numeric(18, 0) NOT NULL,
	NroPTCSucesor numeric(18, 0) NOT NULL,
	FechaHora datetime NULL,
	IdUsuario varchar(30) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PTCVinculados ADD CONSTRAINT
	PK_PTCVinculados PRIMARY KEY CLUSTERED 
	(
	NroPTCPredecesor,
	NroPTCSucesor
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PTCVinculados SET (LOCK_ESCALATION = TABLE)
GO

alter table PTC add EsperandoPorPTCVinculado int;

COMMIT